# Generated by Django 6.0.5 on 2026-05-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='olumn',
            new_name='column',
        ),
    ]
