# Generated by Django 6.0.5 on 2026-05-20 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_board_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
